### ISSUE TITLE
dsc-permutations-and-factorials-lab-v2-1_comments-issue

### ISSUE THREAD

**Issue by tfuger10** [learn-co-curriculum/dsc-permutations-and-factorials-lab-v2-1#2]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x] Other (explain below)

### Source

```
denom_phone_smudge = #or math.factorial(4)
denom_phone_smudge


denom_phone_smudge_2 = #or use math.factorial(4)
denom_phone_smudge_2
```

### Concern

The comments in the notebook suggest to use math.factorial(4) in two separate places. I would just take those comments out of the notebook entirely. The first area where it suggests this does in fact use only math.factorial(4), but the second area is not just using math.factorial(4), it also has to be divided by 2 and multiplied by three. So the comment is at odds with the presentation of the problem.

## (Optional) Proposed Solution

Remove the comments entirely, I would think the student should be able to figure this out

## What OS Are You Using?

- [ ] OS X
- [ X] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by jessepisel** [comment]
Thanks for opening this issue with us @tfuger10 :wave:. I agree that students should be able to follow along without these comments. I have removed them in commit 074c26a8f5c7bf03da47ea750d6844cf831c224e.

I am closing this issue at this time.
